"""baseline schema

Revision ID: 368e99a7dcb4
Revises: 
Create Date: 2026-08-05 02:06:31.660371

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '368e99a7dcb4'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_templates',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('vendor', sa.Enum('MIKROTIK', 'TPLINK', 'UBIQUITI', 'GENERIC', 'ANY', name='templatevendor'), nullable=False),
    sa.Column('config_commands', sa.JSON(), nullable=True),
    sa.Column('jinja2_template', sa.Text(), nullable=True),
    sa.Column('variables_schema', sa.JSON(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagnostic_reports',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('device_id', sa.String(length=12), nullable=False),
    sa.Column('baseline_id', sa.String(length=12), nullable=True),
    sa.Column('current_config', sa.JSON(), nullable=False),
    sa.Column('current_state', sa.JSON(), nullable=False),
    sa.Column('differences', sa.JSON(), nullable=True),
    sa.Column('health_checks', sa.JSON(), nullable=True),
    sa.Column('issues_found', sa.Integer(), nullable=False),
    sa.Column('warnings_found', sa.Integer(), nullable=False),
    sa.Column('is_healthy', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('isp_profiles',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('adapter_name', sa.String(length=64), nullable=False),
    sa.Column('dhcp_server_ip', sa.String(length=45), nullable=True),
    sa.Column('dns_servers', sa.JSON(), nullable=True),
    sa.Column('ntp_servers', sa.JSON(), nullable=True),
    sa.Column('wan_vlan', sa.Integer(), nullable=True),
    sa.Column('wan_pppoe', sa.Boolean(), nullable=False),
    sa.Column('wan_pppoe_username_format', sa.String(length=64), nullable=True),
    sa.Column('custom_settings', sa.JSON(), nullable=True),
    sa.Column('upload_endpoint', sa.Text(), nullable=True),
    sa.Column('upload_api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sites',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('customer_name', sa.String(length=128), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_info', sa.Text(), nullable=True),
    sa.Column('cpe_ip', sa.String(length=45), nullable=True),
    sa.Column('cpe_model', sa.String(length=64), nullable=True),
    sa.Column('wan_ip', sa.String(length=45), nullable=True),
    sa.Column('isp_profile_id', sa.String(length=12), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config_jobs',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('site_id', sa.String(length=12), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('template_id', sa.String(length=12), nullable=True),
    sa.Column('total_devices', sa.Integer(), nullable=False),
    sa.Column('completed_devices', sa.Integer(), nullable=False),
    sa.Column('failed_devices', sa.Integer(), nullable=False),
    sa.Column('log', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('site_id', sa.String(length=12), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('brand', sa.Enum('MIKROTIK', 'TPLINK', 'UBIQUITI', 'UNKNOWN', 'GENERIC', name='devicebrand'), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('firmware_version', sa.String(length=32), nullable=True),
    sa.Column('mac_address', sa.String(length=17), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('subnet_mask', sa.String(length=45), nullable=True),
    sa.Column('admin_user_encrypted', sa.Text(), nullable=True),
    sa.Column('admin_password_encrypted', sa.Text(), nullable=True),
    sa.Column('admin_web_port', sa.Integer(), nullable=False),
    sa.Column('wifi_ssid_encrypted', sa.Text(), nullable=True),
    sa.Column('wifi_password_encrypted', sa.Text(), nullable=True),
    sa.Column('dhcp_mode', sa.Enum('DISABLED', 'ENABLED', 'RELAY', 'UNKNOWN', name='dhcpmode'), nullable=False),
    sa.Column('bridge_mode', sa.Boolean(), nullable=False),
    sa.Column('wifi_enabled', sa.Boolean(), nullable=False),
    sa.Column('custom_config', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('baselines',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('device_id', sa.String(length=12), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('full_config', sa.JSON(), nullable=False),
    sa.Column('running_state', sa.JSON(), nullable=False),
    sa.Column('triggered_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config_job_items',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('job_id', sa.String(length=12), nullable=False),
    sa.Column('device_id', sa.String(length=12), nullable=False),
    sa.Column('device_ip', sa.String(length=45), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['config_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('connection_profiles',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('device_id', sa.String(length=12), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('ssh_host', sa.String(length=128), nullable=False),
    sa.Column('ssh_port', sa.Integer(), nullable=False),
    sa.Column('ssh_user_encrypted', sa.Text(), nullable=True),
    sa.Column('ssh_password_encrypted', sa.Text(), nullable=True),
    sa.Column('ssh_key_path', sa.Text(), nullable=True),
    sa.Column('ssh_command_template', sa.Text(), nullable=True),
    sa.Column('web_admin_url', sa.Text(), nullable=True),
    sa.Column('web_admin_port', sa.Integer(), nullable=False),
    sa.Column('jump_host', sa.String(length=128), nullable=True),
    sa.Column('jump_port', sa.Integer(), nullable=True),
    sa.Column('jump_user_encrypted', sa.Text(), nullable=True),
    sa.Column('jump_password_encrypted', sa.Text(), nullable=True),
    sa.Column('last_success', sa.DateTime(), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connection_profiles')
    op.drop_table('config_job_items')
    op.drop_table('baselines')
    op.drop_table('devices')
    op.drop_table('config_jobs')
    op.drop_table('sites')
    op.drop_table('isp_profiles')
    op.drop_table('diagnostic_reports')
    op.drop_table('config_templates')
    # ### end Alembic commands ###
